baseURL = 'https://64bitmax.github.io/vladan-website/'
languageCode = 'en-us'
title = 'Vladan'
theme = 'silhouette-hugo'

[params]
	author = "Vladan"
	description = "Vladan company website for New World"
	keywords = "new world,blog,company,vladan,antares"